language: java

jdk:
- oraclejdk8

env:
- TERM=dumb

before_install:
   - cd NeuGen

script:
   - ant test

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
