language: java

jdk:
- oraclejdk9

env:
- TERM=dumb

before_install:
   - cd NeuGen

addons:
  apt:
    packages:
      ant

script:
   - ant test

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always

