language: java

jdk:
- oraclejdk7

env:
- TERM=dumb

before_install:
   - cd NeuGen

script:
   - ant test

after_success:
  - mvn cobertura:cobertura coveralls:report

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
