language: java

jdk:
- openjdk10

env:
- TERM=dumb

branches:
  except:
  - devel


before_install:
   - cd NeuGen

script:
   - ant test

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
